version: '3.8'

services:

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - RUN_ROLE=backend
    command: ["./entrypoint.sh"]

  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
