# Generated by Django 5.2.1 on 2025-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название породы'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Самец', 'Самец'), ('Самка', 'Самка')], default='Самец', max_length=6, verbose_name='Пол'),
        ),
    ]
